### ISSUE TITLE
License GPL?

### ISSUE THREAD

**Issue by guettli** [commonsmachinery/tinyxmp#3]
I see that you use the GPL license. 

That's sad. 

I am not allowed to use viral licenses.

Why did you use GPL?

**Comment by artfwo** [comment]
Cannot remember why :) I guess, that would be no problem to change the license to MIT if @zougloub and @jonasob agree with that :)

**Comment by jonasob** [comment]
I wouldn't be so hasty to do this. Using the GPL was, and is, a strategic decision. It's a shame you can not use it @guettli , but we didn't create this for purpose of making something *everyone* can use :)

**Comment by zougloub** [comment]
Thanks for asking @artfwo, though as my contribution is very minor so my opinion should matter in the same way.

I've seen my share of developers completely ignoring code licenses, especially when working on embedded software; I imagine this particular library used mostly in server-side processing code, where the GPLv2 doesn't have much “strategic” impact (vs. AGPL), and given its small size I'd guess that people distributing closed-source software could use the BSD3-licensed exempi via python-xmp-toolkit or reinvent the wheel in less than a few man-days, maybe posting that under MIT terms.

So for this particular library, I would lean towards a MIT switch which would encourage adoption / code reuse and recognize that the library isn't a fundamental, can't-do-without piece of software...

**Comment by jonasob** [comment]
Yes, you're right @zougloub. And this was pretty much the strategy, now that I've refreshed my memory. It was a few years ago :-) GPL for larger code bases and MIT for smaller libraries and server-side tools. So with that, this repo should also have a standard MIT license. Let me commit a correction for that :-)

**Comment by guettli** [comment]
Thank you very much for switching to a non viral license!
